### ISSUE TITLE
re-run samples with new analysis?

### ISSUE THREAD

**Issue by lisa55asil** [tanaes/snakemake_shotqual#2]
I tried to re-run already processed samples with the new Mash add-on by updating the .yaml and Snakefile but I got this error:

An unexpected error has occurred.
Please consider posting the following information to the conda GitHub issue tracker at:
    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : not installed
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /home/cmarotz/miniconda3  (writable)
    default environment : /home/cmarotz/miniconda3
       envs directories : /home/cmarotz/miniconda3/envs
          package cache : /home/cmarotz/miniconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

`$ /home/cmarotz/miniconda3/bin/conda ..checkenv bash kneaddata`

Is there a certain protocol that should be followed when adding additional analyses?

**Comment by lisa55asil** [comment]
*This issue was resolved when I updated the orginal .yaml file and re-ran that instead of copying the original, making the changes, and saving under a different name.

**Comment by tanaes** [comment]
Thanks Lisa! I'll keep an eye out for this Conda error in the future
